USE [master]
GO

/****** Object:  Database [A2016_BDDCS_LaplaceJordan]    Script Date: 13/12/2016 20:37:00 ******/
CREATE DATABASE [A2016_BDDCS_LaplaceJordan]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ALH', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\A2016_BDDCS_LaplaceJordan.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ALH_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\A2016_BDDCS_LaplaceJordan_log.ldf' , SIZE = 2816KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [A2016_BDDCS_LaplaceJordan] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [A2016_BDDCS_LaplaceJordan].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [A2016_BDDCS_LaplaceJordan] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [A2016_BDDCS_LaplaceJordan] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [A2016_BDDCS_LaplaceJordan] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [A2016_BDDCS_LaplaceJordan] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [A2016_BDDCS_LaplaceJordan] SET ARITHABORT OFF 
GO

ALTER DATABASE [A2016_BDDCS_LaplaceJordan] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [A2016_BDDCS_LaplaceJordan] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [A2016_BDDCS_LaplaceJordan] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [A2016_BDDCS_LaplaceJordan] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [A2016_BDDCS_LaplaceJordan] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [A2016_BDDCS_LaplaceJordan] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [A2016_BDDCS_LaplaceJordan] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [A2016_BDDCS_LaplaceJordan] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [A2016_BDDCS_LaplaceJordan] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [A2016_BDDCS_LaplaceJordan] SET  DISABLE_BROKER 
GO

ALTER DATABASE [A2016_BDDCS_LaplaceJordan] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [A2016_BDDCS_LaplaceJordan] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [A2016_BDDCS_LaplaceJordan] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [A2016_BDDCS_LaplaceJordan] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [A2016_BDDCS_LaplaceJordan] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [A2016_BDDCS_LaplaceJordan] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [A2016_BDDCS_LaplaceJordan] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [A2016_BDDCS_LaplaceJordan] SET RECOVERY FULL 
GO

ALTER DATABASE [A2016_BDDCS_LaplaceJordan] SET  MULTI_USER 
GO

ALTER DATABASE [A2016_BDDCS_LaplaceJordan] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [A2016_BDDCS_LaplaceJordan] SET DB_CHAINING OFF 
GO

ALTER DATABASE [A2016_BDDCS_LaplaceJordan] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [A2016_BDDCS_LaplaceJordan] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [A2016_BDDCS_LaplaceJordan] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [A2016_BDDCS_LaplaceJordan] SET  READ_WRITE 
GO

